from setuptools import setup

setup(
    name='sqlite3-to-mysql',
    version='1.1.0',
    packages=['env.lib.python3.7.site-packages.pip', 'env.lib.python3.7.site-packages.pip._vendor',
              'env.lib.python3.7.site-packages.pip._vendor.idna', 'env.lib.python3.7.site-packages.pip._vendor.pep517',
              'env.lib.python3.7.site-packages.pip._vendor.pytoml',
              'env.lib.python3.7.site-packages.pip._vendor.certifi',
              'env.lib.python3.7.site-packages.pip._vendor.chardet',
              'env.lib.python3.7.site-packages.pip._vendor.chardet.cli',
              'env.lib.python3.7.site-packages.pip._vendor.distlib',
              'env.lib.python3.7.site-packages.pip._vendor.distlib._backport',
              'env.lib.python3.7.site-packages.pip._vendor.msgpack',
              'env.lib.python3.7.site-packages.pip._vendor.urllib3',
              'env.lib.python3.7.site-packages.pip._vendor.urllib3.util',
              'env.lib.python3.7.site-packages.pip._vendor.urllib3.contrib',
              'env.lib.python3.7.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'env.lib.python3.7.site-packages.pip._vendor.urllib3.packages',
              'env.lib.python3.7.site-packages.pip._vendor.urllib3.packages.backports',
              'env.lib.python3.7.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'env.lib.python3.7.site-packages.pip._vendor.colorama',
              'env.lib.python3.7.site-packages.pip._vendor.html5lib',
              'env.lib.python3.7.site-packages.pip._vendor.html5lib._trie',
              'env.lib.python3.7.site-packages.pip._vendor.html5lib.filters',
              'env.lib.python3.7.site-packages.pip._vendor.html5lib.treewalkers',
              'env.lib.python3.7.site-packages.pip._vendor.html5lib.treeadapters',
              'env.lib.python3.7.site-packages.pip._vendor.html5lib.treebuilders',
              'env.lib.python3.7.site-packages.pip._vendor.lockfile',
              'env.lib.python3.7.site-packages.pip._vendor.progress',
              'env.lib.python3.7.site-packages.pip._vendor.requests',
              'env.lib.python3.7.site-packages.pip._vendor.packaging',
              'env.lib.python3.7.site-packages.pip._vendor.cachecontrol',
              'env.lib.python3.7.site-packages.pip._vendor.cachecontrol.caches',
              'env.lib.python3.7.site-packages.pip._vendor.webencodings',
              'env.lib.python3.7.site-packages.pip._vendor.pkg_resources',
              'env.lib.python3.7.site-packages.pip._internal', 'env.lib.python3.7.site-packages.pip._internal.cli',
              'env.lib.python3.7.site-packages.pip._internal.req', 'env.lib.python3.7.site-packages.pip._internal.vcs',
              'env.lib.python3.7.site-packages.pip._internal.utils',
              'env.lib.python3.7.site-packages.pip._internal.models',
              'env.lib.python3.7.site-packages.pip._internal.commands',
              'env.lib.python3.7.site-packages.pip._internal.operations', 'env.lib.python3.7.site-packages.tqdm',
              'env.lib.python3.7.site-packages.tqdm.auto', 'env.lib.python3.7.site-packages.tqdm.autonotebook',
              'env.lib.python3.7.site-packages.mysql', 'env.lib.python3.7.site-packages.mysql.connector',
              'env.lib.python3.7.site-packages.mysql.connector.django',
              'env.lib.python3.7.site-packages.mysql.connector.locales',
              'env.lib.python3.7.site-packages.mysql.connector.locales.eng',
              'env.lib.python3.7.site-packages.google.protobuf', 'env.lib.python3.7.site-packages.google.protobuf.util',
              'env.lib.python3.7.site-packages.google.protobuf.pyext',
              'env.lib.python3.7.site-packages.google.protobuf.compiler',
              'env.lib.python3.7.site-packages.google.protobuf.internal',
              'env.lib.python3.7.site-packages.google.protobuf.internal.import_test_package',
              'env.lib.python3.7.site-packages.mysqlx', 'env.lib.python3.7.site-packages.mysqlx.locales',
              'env.lib.python3.7.site-packages.mysqlx.locales.eng', 'env.lib.python3.7.site-packages.mysqlx.protobuf',
              'env.lib.python3.7.site-packages.setuptools', 'env.lib.python3.7.site-packages.setuptools.extern',
              'env.lib.python3.7.site-packages.setuptools._vendor',
              'env.lib.python3.7.site-packages.setuptools._vendor.packaging',
              'env.lib.python3.7.site-packages.setuptools.command', 'env.lib.python3.7.site-packages.pkg_resources',
              'env.lib.python3.7.site-packages.pkg_resources.extern',
              'env.lib.python3.7.site-packages.pkg_resources._vendor',
              'env.lib.python3.7.site-packages.pkg_resources._vendor.packaging'],
    url='',
    license='MIT',
    author='Klemen Tušar',
    author_email='techouse@gmail.com',
    description='A simple Python 3 script to transfer data from SQLite3 to MySQL.'
)
